__version__: 1.4.4
transform:
  __class_fullname__: Compose
  additional_targets: {}
  bbox_params: null
  is_check_shapes: true
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: Resize
    always_apply: false
    height: 224
    interpolation: 1
    p: 1.0
    width: 224
  - __class_fullname__: HorizontalFlip
    always_apply: false
    p: 0.5
  - __class_fullname__: ShiftScaleRotate
    always_apply: false
    border_mode: 4
    interpolation: 1
    mask_value: 0.0
    p: 0.5
    rotate_limit:
    - -20
    - 20
    rotate_method: largest_box
    scale_limit:
    - -0.09999999999999998
    - 0.10000000000000009
    shift_limit_x:
    - -0.05
    - 0.05
    shift_limit_y:
    - -0.05
    - 0.05
    value: 0.0
  - __class_fullname__: RandomBrightnessContrast
    always_apply: false
    brightness_by_max: true
    brightness_limit:
    - -0.2
    - 0.2
    contrast_limit:
    - -0.2
    - 0.2
    p: 0.5
  - __class_fullname__: CoarseDropout
    always_apply: false
    fill_value: 0.0
    mask_fill_value: null
    max_height: 20
    max_holes: 5
    max_width: 20
    min_height: 20
    min_holes: 5
    min_width: 20
    p: 0.5
  - __class_fullname__: Normalize
    always_apply: false
    max_pixel_value: 255.0
    mean:
    - 0.485
    - 0.456
    - 0.406
    normalization: standard
    p: 1.0
    std:
    - 0.229
    - 0.224
    - 0.225
  - __class_fullname__: ToTensorV2
    always_apply: true
    p: 1.0
    transpose_mask: false
